apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: navbar-deployment
spec:
  replicas: 3 # tells deployment to run 3 pod matching the selector
  selector:
    matchLabels:
      app: helloworld
  template: # pod templates
    metadata:
      labels:
        app: helloworld
        env: prod
        author: himanshu
        tier: ui
        release-version: "1.0"
    spec:
      containers:
        - name: helloworld
          image: karthequian/helloworld:black
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: navbar-service
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
