apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rvstore-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rvstore-ui
  template:
    metadata:
      labels:
        app: rvstore-ui
    spec:
      containers:
      - image: vergeops/k8s-rvstore-ui:1.0
        name:  rvstore-ui
---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-ui
spec:
  selector:
    app: rvstore-ui
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30081
  type: NodePort
